import { Building2, CheckCircle2, Search, Users } from "lucide-react";

const permisosDemo = [
  { codigo: "USUARIOS.CREAR", nombre: "Crear usuarios", modulo: "Usuarios", descripcion: "Registrar usuarios y asignarlos a un laboratorio.", asignado: true },
  { codigo: "USUARIOS.EDITAR", nombre: "Editar usuarios", modulo: "Usuarios", descripcion: "Modificar datos de usuarios de la organización.", asignado: true },
  { codigo: "QC.REGISTRAR", nombre: "Registrar control QC", modulo: "Análisis QC", descripcion: "Ingresar resultados de controles de calidad.", asignado: true },
  { codigo: "QC.VALIDAR", nombre: "Validar controles QC", modulo: "Análisis QC", descripcion: "Validar técnicamente resultados de control.", asignado: false },
  { codigo: "LABORATORIOS.EDITAR", nombre: "Editar laboratorios", modulo: "Laboratorios", descripcion: "Modificar información de instituciones registradas.", asignado: false },
];

export default function PaginaAsignacionPermisos() {
  return <main className="min-h-screen bg-canvas px-4 py-7 sm:px-7 sm:py-9 lg:px-10"><div className="mx-auto max-w-[1440px]">
    <header className="border-b border-line pb-6"><p className="mb-3 text-[11px] font-bold uppercase tracking-[0.18em] text-ink-faint">Administración de acceso</p><h1 className="text-3xl font-semibold tracking-[-0.04em] text-ink sm:text-[34px]">Asignación de permisos</h1><p className="mt-2 text-sm text-ink-muted">Configura los permisos disponibles para cada tipo de usuario del sistema.</p></header>
    <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(320px,0.65fr)_minmax(0,1.35fr)]"><aside className="h-fit rounded-xl border border-line bg-surface p-5 shadow-[0_1px_2px_rgb(0_0_0_/_0.02)] sm:p-6"><div className="flex size-10 items-center justify-center rounded-lg bg-status-info-soft text-status-info"><Users className="size-5" /></div><p className="mt-5 text-base font-semibold tracking-[-0.02em] text-ink">Rol seleccionado</p><p className="mt-1 text-xs text-ink-muted">Elige el perfil al que deseas asignar permisos.</p><label className="mt-5 flex flex-col gap-1.5"><span className="text-[11px] font-bold uppercase tracking-[0.1em] text-ink-faint">Tipo de usuario</span><select defaultValue="Tecnólogo Médico General" className="h-10 rounded-lg border border-line bg-canvas px-3 text-sm font-medium text-ink outline-none focus:border-line-strong"><option>Administrador</option><option>Tecnólogo Médico General</option><option>Tecnólogo Médico Química Clínica</option><option>Jefatura de Laboratorio</option><option>Supervisor QC</option></select></label><div className="mt-5 rounded-lg bg-surface-muted p-4"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-ink-faint">Resumen de maqueta</p><div className="mt-3 space-y-2 text-sm"><p className="flex items-center justify-between"><span className="text-ink-muted">Permisos asignados</span><span className="font-semibold text-status-ok">3</span></p><p className="flex items-center justify-between"><span className="text-ink-muted">Permisos disponibles</span><span className="font-semibold text-ink">5</span></p></div></div><p className="mt-5 text-xs leading-5 text-ink-muted">Selecciona o deselecciona las casillas de la tabla para representar la asignación del rol.</p></aside>
      <section className="overflow-hidden rounded-xl border border-line bg-surface shadow-[0_1px_2px_rgb(0_0_0_/_0.02)]"><div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-base font-semibold tracking-[-0.02em] text-ink">Permisos del rol</p><p className="mt-1 text-xs text-ink-muted">Tecnólogo Médico General · selección visual</p></div><div className="relative w-full sm:w-64"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-ink-faint" /><input placeholder="Buscar permiso..." className="h-10 w-full rounded-lg border border-line bg-canvas pl-9 pr-3 text-sm outline-none placeholder:text-ink-faint focus:border-line-strong" /></div></div><div className="overflow-x-auto"><table className="min-w-[800px] w-full text-left"><thead className="border-b border-line bg-surface-muted/70 text-[10px] font-bold uppercase tracking-[0.12em] text-ink-faint"><tr><th className="w-16 px-5 py-3.5 text-center">Asignar</th><th className="px-4 py-3.5">Código / permiso</th><th className="px-4 py-3.5">Módulo</th><th className="px-4 py-3.5">Descripción</th><th className="px-5 py-3.5 text-right">Estado</th></tr></thead><tbody className="divide-y divide-line">{permisosDemo.map((permiso) => <tr key={permiso.codigo} className="transition hover:bg-surface-muted/50"><td className="px-5 py-4 text-center"><input type="checkbox" defaultChecked={permiso.asignado} aria-label={`Asignar ${permiso.nombre}`} className="size-4 rounded border-line text-ink accent-ink" /></td><td className="px-4 py-4"><p className="font-mono text-[11px] font-semibold text-status-info">{permiso.codigo}</p><p className="mt-1 font-semibold text-ink">{permiso.nombre}</p></td><td className="px-4 py-4"><span className="inline-flex items-center gap-1 text-xs font-medium text-ink-muted"><Building2 className="size-3.5 text-ink-faint" />{permiso.modulo}</span></td><td className="max-w-xs px-4 py-4 text-sm leading-5 text-ink-muted">{permiso.descripcion}</td><td className="px-5 py-4 text-right"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-bold ${permiso.asignado ? "bg-status-ok-soft text-status-ok" : "bg-surface-muted text-ink-muted"}`}><span className="size-1.5 rounded-full bg-current" />{permiso.asignado ? "Asignado" : "Sin asignar"}</span></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-line bg-surface-muted/50 px-5 py-3"><p className="text-xs text-ink-muted">Los cambios son visuales y no se guardan.</p><button type="button" className="inline-flex h-9 items-center gap-2 rounded-lg bg-ink px-3.5 text-xs font-semibold text-white transition hover:bg-accent-strong"><CheckCircle2 className="size-3.5" />Guardar asignación</button></div></section>
    </section>
  </div></main>;
}
