import { CheckCircle2, ClipboardCheck, Pencil, Plus, Power, Search, ShieldCheck } from "lucide-react";

const permisosDemo = [
  { id: 1, codigo: "USUARIOS.CREAR", nombre: "Crear usuarios", modulo: "Usuarios", accion: "Crear", descripcion: "Permite registrar nuevos usuarios y asignarlos a un laboratorio clínico.", activo: true, creacion: "15 ene. 2026, 09:30", modificacion: "20 ago. 2026, 11:15", creador: 1, modificador: 1 },
  { id: 2, codigo: "QC.VALIDAR", nombre: "Validar controles QC", modulo: "Análisis QC", accion: "Validar", descripcion: "Autoriza la validación técnica de resultados de control de calidad.", activo: true, creacion: "15 ene. 2026, 09:32", modificacion: "18 ago. 2026, 14:20", creador: 1, modificador: 2 },
  { id: 3, codigo: "LABORATORIOS.EDITAR", nombre: "Editar laboratorios", modulo: "Laboratorios", accion: "Editar", descripcion: "Permite modificar la información administrativa de instituciones registradas.", activo: false, creacion: "16 ene. 2026, 10:10", modificacion: "02 ago. 2026, 16:45", creador: 1, modificador: 1 },
];

function Campo({ etiqueta, placeholder }) {
  return <label className="flex flex-col gap-1.5"><span className="text-[11px] font-bold uppercase tracking-[0.1em] text-ink-faint">{etiqueta}</span><input placeholder={placeholder} className="h-10 rounded-lg border border-line bg-canvas px-3 text-sm text-ink outline-none placeholder:text-ink-faint focus:border-line-strong" /></label>;
}

export default function PaginaPermisosSistema() {
  return <main className="min-h-screen bg-canvas px-4 py-7 sm:px-7 sm:py-9 lg:px-10"><div className="mx-auto max-w-[1440px]">
    <header className="flex flex-col gap-5 border-b border-line pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-3 text-[11px] font-bold uppercase tracking-[0.18em] text-ink-faint">Administración de acceso</p><h1 className="text-3xl font-semibold tracking-[-0.04em] text-ink sm:text-[34px]">Permisos del sistema</h1><p className="mt-2 text-sm text-ink-muted">Define las acciones autorizadas por módulo dentro de Levey QC.</p></div><button type="button" popoverTarget="formulario-permiso" className="inline-flex h-10 items-center gap-2 rounded-lg bg-ink px-4 text-sm font-semibold text-white transition hover:bg-accent-strong"><Plus className="size-4" />Nuevo permiso</button></header>
    <section className="mt-6 overflow-hidden rounded-xl border border-line bg-surface shadow-[0_1px_2px_rgb(0_0_0_/_0.02)]"><div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-base font-semibold tracking-[-0.02em] text-ink">Listado de permisos</p><p className="mt-1 text-xs text-ink-muted">Acciones disponibles y trazabilidad de administración</p></div><div className="relative w-full sm:w-80"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-ink-faint" /><input placeholder="Buscar por código, módulo o acción..." className="h-10 w-full rounded-lg border border-line bg-canvas pl-9 pr-3 text-sm outline-none placeholder:text-ink-faint focus:border-line-strong" /></div></div>
      <div className="overflow-x-auto"><table className="min-w-[1320px] w-full text-left"><thead className="border-b border-line bg-surface-muted/70 text-[10px] font-bold uppercase tracking-[0.12em] text-ink-faint"><tr><th className="px-5 py-3.5">ID</th><th className="px-4 py-3.5">Código / permiso</th><th className="px-4 py-3.5">Módulo</th><th className="px-4 py-3.5">Acción</th><th className="px-4 py-3.5">Descripción</th><th className="px-4 py-3.5">Estado</th><th className="px-4 py-3.5">Creación</th><th className="px-4 py-3.5">Modificación</th><th className="px-5 py-3.5 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-line">{permisosDemo.map((permiso) => <tr key={permiso.id} className="transition hover:bg-surface-muted/50"><td className="px-5 py-4 text-sm font-medium text-ink-muted">#{permiso.id}</td><td className="px-4 py-4"><p className="font-mono text-[11px] font-semibold text-status-info">{permiso.codigo}</p><p className="mt-1 font-semibold text-ink">{permiso.nombre}</p></td><td className="px-4 py-4 text-sm font-medium text-ink-muted">{permiso.modulo}</td><td className="px-4 py-4"><span className="rounded-md bg-surface-muted px-2 py-1 text-xs font-semibold text-ink-muted">{permiso.accion}</span></td><td className="max-w-[280px] px-4 py-4 text-sm leading-5 text-ink-muted">{permiso.descripcion}</td><td className="px-4 py-4"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-bold ${permiso.activo ? "bg-status-ok-soft text-status-ok" : "bg-surface-muted text-ink-muted"}`}><span className="size-1.5 rounded-full bg-current" />{permiso.activo ? "Activo" : "Inactivo"}</span></td><td className="px-4 py-4 text-xs text-ink-muted"><p>{permiso.creacion}</p><p className="mt-1 text-ink-faint">Usuario #{permiso.creador}</p></td><td className="px-4 py-4 text-xs text-ink-muted"><p>{permiso.modificacion}</p><p className="mt-1 text-ink-faint">Usuario #{permiso.modificador}</p></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button type="button" popoverTarget="formulario-permiso" className="inline-flex h-8 items-center gap-1.5 rounded-md border border-line bg-surface px-2.5 text-[11px] font-semibold text-ink transition hover:border-line-strong hover:bg-surface-muted"><Pencil className="size-3.5 text-ink-muted" />Editar</button><button type="button" title={permiso.activo ? "Desactivar permiso" : "Activar permiso"} className={`flex size-8 items-center justify-center rounded-md border transition ${permiso.activo ? "border-status-alert-soft bg-surface text-status-alert hover:bg-status-alert-soft" : "border-status-ok-soft bg-surface text-status-ok hover:bg-status-ok-soft"}`}><Power className="size-3.5" /></button></div></td></tr>)}</tbody></table></div>
      <div className="border-t border-line bg-surface-muted/50 px-5 py-3 text-xs text-ink-muted">Mostrando <span className="font-semibold text-ink">{permisosDemo.length}</span> permisos registrados.</div>
    </section>
    <div id="formulario-permiso" popover="auto" className="m-auto max-h-[88vh] w-[min(620px,calc(100vw-2rem))] overflow-y-auto rounded-2xl border border-line bg-surface p-5 shadow-2xl backdrop:bg-black/35 sm:p-6"><div className="flex items-center gap-3 border-b border-line pb-4"><div className="flex size-10 items-center justify-center rounded-lg bg-ink text-white"><ClipboardCheck className="size-5" /></div><div className="flex-1"><p className="font-semibold tracking-[-0.02em] text-ink">Permiso del sistema</p><p className="text-xs text-ink-muted">Creación o edición visual de permiso</p></div><button type="button" popoverTarget="formulario-permiso" popoverTargetAction="hide" className="rounded-md px-3 py-2 text-xs font-semibold text-ink-muted transition hover:bg-surface-muted hover:text-ink">Cerrar</button></div><div className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Campo etiqueta="Código de permiso" placeholder="Ej. QC.VALIDAR" /><Campo etiqueta="Nombre del permiso" placeholder="Ej. Validar controles QC" /><Campo etiqueta="Módulo" placeholder="Ej. Análisis QC" /><Campo etiqueta="Acción" placeholder="Ej. Validar" /></div><label className="flex flex-col gap-1.5"><span className="text-[11px] font-bold uppercase tracking-[0.1em] text-ink-faint">Descripción</span><textarea rows="4" placeholder="Describe qué permite hacer este permiso..." className="resize-none rounded-lg border border-line bg-canvas px-3 py-2.5 text-sm text-ink outline-none placeholder:text-ink-faint focus:border-line-strong" /></label><label className="flex flex-col gap-1.5"><span className="text-[11px] font-bold uppercase tracking-[0.1em] text-ink-faint">Estado</span><select className="h-10 rounded-lg border border-line bg-canvas px-3 text-sm text-ink outline-none focus:border-line-strong"><option>Activo</option><option>Inactivo</option></select></label><button type="button" className="flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-ink text-sm font-semibold text-white transition hover:bg-accent-strong"><CheckCircle2 className="size-4" />Guardar permiso</button><p className="text-center text-[11px] leading-4 text-ink-faint">Acción visual sin conexión ni persistencia configurada.</p></div></div>
  </div></main>;
}
